### PR TITLE
Update 'require' in ES and README

### PR DESCRIPTION
**Pull request by Tineshnehete**
- Updated the require statements to ES module syntax for better compatibility and modern code practices.
- Revised the README to reflect the changes and provide clearer instructions.

This PR ensures that the codebase is up-to-date with ES standards and improves the documentation for better user guidance.

### CODE REVIEW

**Comment by nirmalchandra** [comment]
Thanks @Tineshnehete, let us merge to an intermediate branch, if the Cloudflare build passes and the hostings gets through, then we(I will) can merge to main. How does it sound? Is that ok with you @Tineshnehete ?

or
You are saying, you have tested it already? All ok?

**Comment by Tineshnehete** [comment]
HI @nirmalchandra  can review now

**Comment by nirmalchandra** [comment]
> HI @nirmalchandra can review now

Happy to approve and mege, did you check the CloudFlare logs (in your CF console from your forked branch) and you're happy, it's no more failing?

**Comment by nirmalchandra** [comment]
Check here, the Build Passed, but still getting "404 - Page not found". 🔴 
Can you check and fix this @Tineshnehete ? Could be a minor issue.

Build Out:
https://github.com/authorjapps/zerocode-tdd-docs/runs/31453615205

Site:
https://staging-main.zerocode-tdd-docs.pages.dev
image

**Pull request merged**
